/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
    
    public static void main(String[] args) {
      System.out.println("testing main class");
    }
}
